Test

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -12,153 +12,153 @@ on:
       - ready_for_review
 
 jobs:
-  format:
-    name: 👔 Format
-    runs-on: ubuntu-latest
-    steps:
-      - name: 📥 Checkout repo
-        uses: actions/checkout@v4
+  # format:
+  #   name: 👔 Format
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: 📥 Checkout repo
+  #       uses: actions/checkout@v4
 
-      - name: ⎔ Setup node
-        uses: actions/setup-node@v4
-        with:
-          node-version: 20.x
-          cache: npm
+  #     - name: ⎔ Setup node
+  #       uses: actions/setup-node@v4
+  #       with:
+  #         node-version: 20.x
+  #         cache: npm
 
-      - name: 📦 Install dependencies
-        run: npm ci
+  #     - name: 📦 Install dependencies
+  #       run: npm ci
 
-      - name: 👔 Format
-        run: npm run format:check
+  #     - name: 👔 Format
+  #       run: npm run format:check
 
-  lint:
-    name: ⬣ ESLint
-    runs-on: ubuntu-latest
-    steps:
-      - name: 📥 Checkout repo
-        uses: actions/checkout@v4
+  # lint:
+  #   name: ⬣ ESLint
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: 📥 Checkout repo
+  #       uses: actions/checkout@v4
 
-      - name: ⎔ Setup node
-        uses: actions/setup-node@v4
-        with:
-          node-version: 20.x
-          cache: npm
+  #     - name: ⎔ Setup node
+  #       uses: actions/setup-node@v4
+  #       with:
+  #         node-version: 20.x
+  #         cache: npm
 
-      - name: 📦 Install dependencies
-        run: npm ci
+  #     - name: 📦 Install dependencies
+  #       run: npm ci
 
-      - name: ⬣ Lint
-        run: npm run lint
+  #     - name: ⬣ Lint
+  #       run: npm run lint
 
-  types:
-    name: ʦ Types check
-    runs-on: ubuntu-latest
-    steps:
-      - name: 📥 Checkout repo
-        uses: actions/checkout@v4
+  # types:
+  #   name: ʦ Types check
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: 📥 Checkout repo
+  #       uses: actions/checkout@v4
 
-      - name: ⎔ Setup node
-        uses: actions/setup-node@v4
-        with:
-          node-version: 20.x
-          cache: npm
+  #     - name: ⎔ Setup node
+  #       uses: actions/setup-node@v4
+  #       with:
+  #         node-version: 20.x
+  #         cache: npm
 
-      - name: 📦 Install dependencies
-        run: npm ci
+  #     - name: 📦 Install dependencies
+  #       run: npm ci
 
-      - name: ʦ Types check
-        run: npm run test:types
+  #     - name: ʦ Types check
+  #       run: npm run test:types
 
-  unit-tests:
-    name: ⚡️ Unit tests
-    runs-on: ubuntu-latest
-    steps:
-      - name: 📥 Checkout repo
-        uses: actions/checkout@v4
+  # unit-tests:
+  #   name: ⚡️ Unit tests
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: 📥 Checkout repo
+  #       uses: actions/checkout@v4
 
-      - name: ⎔ Setup node
-        uses: actions/setup-node@v4
-        with:
-          node-version: 20.x
-          cache: npm
+  #     - name: ⎔ Setup node
+  #       uses: actions/setup-node@v4
+  #       with:
+  #         node-version: 20.x
+  #         cache: npm
 
-      - name: 📦 Install dependencies
-        run: npm ci
+  #     - name: 📦 Install dependencies
+  #       run: npm ci
 
-      - name: ⚡️ Run Vitest
-        run: npm run test:coverage
+  #     - name: ⚡️ Run Vitest
+  #       run: npm run test:coverage
 
-  e2e-tests:
-    name: 🎭 E2E tests
-    timeout-minutes: 30
-    runs-on: ubuntu-latest
-    needs: [format, lint, types, unit-tests]
-    steps:
-      - name: 📥 Checkout repo
-        uses: actions/checkout@v4
+  # e2e-tests:
+  #   name: 🎭 E2E tests
+  #   timeout-minutes: 30
+  #   runs-on: ubuntu-latest
+  #   needs: [format, lint, types, unit-tests]
+  #   steps:
+  #     - name: 📥 Checkout repo
+  #       uses: actions/checkout@v4
 
-      - name: ⎔ Setup node
-        uses: actions/setup-node@v4
-        with:
-          node-version: 20.16
-          cache: npm
+  #     - name: ⎔ Setup node
+  #       uses: actions/setup-node@v4
+  #       with:
+  #         node-version: 20.16
+  #         cache: npm
 
-      - name: 📦 Install dependencies
-        run: npm ci
+  #     - name: 📦 Install dependencies
+  #       run: npm ci
 
-      - name: 📋 Copy environment variables
-        run: cp .dev.vars.example .dev.vars
+  #     - name: 📋 Copy environment variables
+  #       run: cp .dev.vars.example .dev.vars
 
-      - name: 🏷️ Store Playwright Version
-        run: echo "PLAYWRIGHT_VERSION=`npx playwright -V | cut -d ' ' -f2`" >> $GITHUB_ENV
+  #     - name: 🏷️ Store Playwright Version
+  #       run: echo "PLAYWRIGHT_VERSION=`npx playwright -V | cut -d ' ' -f2`" >> $GITHUB_ENV
 
-      - name: 📝 Cache Playwright Browsers
-        id: cache-playwright-browsers
-        uses: actions/cache@v4
-        with:
-          path: ~/.cache/ms-playwright
-          key: playwright-browsers-${{ env.PLAYWRIGHT_VERSION }}
+  #     - name: 📝 Cache Playwright Browsers
+  #       id: cache-playwright-browsers
+  #       uses: actions/cache@v4
+  #       with:
+  #         path: ~/.cache/ms-playwright
+  #         key: playwright-browsers-${{ env.PLAYWRIGHT_VERSION }}
 
-      - name: 📦 Install Playwright Browsers
-        if: steps.cache-playwright-browsers.outputs.cache-hit != 'true'
-        run: npx playwright install --with-deps chromium
+  #     - name: 📦 Install Playwright Browsers
+  #       if: steps.cache-playwright-browsers.outputs.cache-hit != 'true'
+  #       run: npx playwright install --with-deps chromium
 
-      - name: 🛠️ Build
-        run: npm run build
+  #     - name: 🛠️ Build
+  #       run: npm run build
 
-      - name: 🗄️ Database setup
-        run: npm run db:setup
+  #     - name: 🗄️ Database setup
+  #       run: npm run db:setup
 
-      - name: 🎭 Run Playwright tests
-        run: npm run test:e2e
+  #     - name: 🎭 Run Playwright tests
+  #       run: npm run test:e2e
 
-  database:
-    name: 🚚 Database migration
-    runs-on: ubuntu-latest
-    needs: [e2e-tests]
-    if: github.ref == 'refs/heads/main' || github.event.pull_request.draft == false
-    concurrency:
-      group: database-${{ github.ref == 'refs/heads/main' && 'production' || 'preview' }}
-    env:
-      CLOUDFLARE_ACCOUNT_ID: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
-      CLOUDFLARE_DATABASE_ID: ${{ github.ref == 'refs/heads/main' && vars.CLOUDFLARE_DATABASE_ID_PRODUCTION || vars.CLOUDFLARE_DATABASE_ID_PREVIEW }}
-    steps:
-      - name: 📥 Checkout repo
-        uses: actions/checkout@v4
+  # database:
+  #   name: 🚚 Database migration
+  #   runs-on: ubuntu-latest
+  #   needs: [e2e-tests]
+  #   if: github.ref == 'refs/heads/main' || github.event.pull_request.draft == false
+  #   concurrency:
+  #     group: database-${{ github.ref == 'refs/heads/main' && 'production' || 'preview' }}
+  #   env:
+  #     CLOUDFLARE_ACCOUNT_ID: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
+  #     CLOUDFLARE_DATABASE_ID: ${{ github.ref == 'refs/heads/main' && vars.CLOUDFLARE_DATABASE_ID_PRODUCTION || vars.CLOUDFLARE_DATABASE_ID_PREVIEW }}
+  #   steps:
+  #     - name: 📥 Checkout repo
+  #       uses: actions/checkout@v4
 
-      - name: ⎔ Setup node
-        uses: actions/setup-node@v4
-        with:
-          node-version: 20.x
-          cache: npm
+  #     - name: ⎔ Setup node
+  #       uses: actions/setup-node@v4
+  #       with:
+  #         node-version: 20.x
+  #         cache: npm
 
-      - name: 📦 Install dependencies
-        run: npm ci
+  #     - name: 📦 Install dependencies
+  #       run: npm ci
 
-      - name: 🚚 Database migration
-        run: npx drizzle-kit migrate --config ./db/drizzle.remote.config.ts
-        env:
-          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
+  #     - name: 🚚 Database migration
+  #       run: npx drizzle-kit migrate --config ./db/drizzle.remote.config.ts
+  #       env:
+  #         CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
 
   deploy:
     name: 🚀 Deploy
@@ -194,42 +194,116 @@ jobs:
           command: pages deploy build/client --project-name=${{ vars.CLOUDFLARE_PROJECT_NAME }}
           gitHubToken: ${{ secrets.GITHUB_TOKEN }}
 
-  smoke-tests:
-    name: 🚬 Smoke tests
-    timeout-minutes: 15
+  # smoke-tests:
+  #   name: 🚬 Smoke tests
+  #   timeout-minutes: 15
+  #   runs-on: ubuntu-latest
+  #   needs: [deploy]
+  #   if: ${{ vars.CLOUDFLARE_ACCESS_CLIENT_ID }}
+  #   steps:
+  #     - name: 📥 Checkout repo
+  #       uses: actions/checkout@v4
+
+  #     - name: ⎔ Setup node
+  #       uses: actions/setup-node@v4
+  #       with:
+  #         node-version: 20.16.0
+  #         cache: npm
+
+  #     - name: 📦 Install dependencies
+  #       run: npm ci
+
+  #     - name: 🏷️ Store Playwright Version
+  #       run: echo "PLAYWRIGHT_VERSION=`npx playwright -V | cut -d ' ' -f2`" >> $GITHUB_ENV
+
+  #     - name: 📝 Cache Playwright Browsers
+  #       id: cache-playwright-browsers
+  #       uses: actions/cache@v4
+  #       with:
+  #         path: ~/.cache/ms-playwright
+  #         key: playwright-browsers-${{ env.PLAYWRIGHT_VERSION }}
+
+  #     - name: 📦 Install Playwright Browsers
+  #       if: steps.cache-playwright-browsers.outputs.cache-hit != 'true'
+  #       run: npx playwright install --with-deps chromium
+
+  #     - name: 🚬 Run smoke tests
+  #       run: npm run test:smoke
+  #       env:
+  #         TEST_PAGE_URL: ${{ needs.deploy.outputs.page_url }}
+  #         CLOUDFLARE_ACCESS_CLIENT_ID: ${{ vars.CLOUDFLARE_ACCESS_CLIENT_ID }}
+  #         CLOUDFLARE_ACCESS_CLIENT_SECRET: ${{ secrets.CLOUDFLARE_ACCESS_CLIENT_SECRET }}
+
+  cleanup:
+    name: 🧹 Deploy Cleanup
     runs-on: ubuntu-latest
     needs: [deploy]
-    if: ${{ vars.CLOUDFLARE_ACCESS_CLIENT_ID }}
     steps:
-      - name: 📥 Checkout repo
-        uses: actions/checkout@v4
-
-      - name: ⎔ Setup node
-        uses: actions/setup-node@v4
-        with:
-          node-version: 20.16.0
-          cache: npm
-
-      - name: 📦 Install dependencies
-        run: npm ci
-
-      - name: 🏷️ Store Playwright Version
-        run: echo "PLAYWRIGHT_VERSION=`npx playwright -V | cut -d ' ' -f2`" >> $GITHUB_ENV
-
-      - name: 📝 Cache Playwright Browsers
-        id: cache-playwright-browsers
-        uses: actions/cache@v4
-        with:
-          path: ~/.cache/ms-playwright
-          key: playwright-browsers-${{ env.PLAYWRIGHT_VERSION }}
-
-      - name: 📦 Install Playwright Browsers
-        if: steps.cache-playwright-browsers.outputs.cache-hit != 'true'
-        run: npx playwright install --with-deps chromium
-
-      - name: 🚬 Run smoke tests
-        run: npm run test:smoke
+      - name: 🔍 Find deployment ID
         env:
-          TEST_PAGE_URL: ${{ needs.deploy.outputs.page_url }}
-          CLOUDFLARE_ACCESS_CLIENT_ID: ${{ vars.CLOUDFLARE_ACCESS_CLIENT_ID }}
-          CLOUDFLARE_ACCESS_CLIENT_SECRET: ${{ secrets.CLOUDFLARE_ACCESS_CLIENT_SECRET }}
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          # Fetch deployment event data for this PR
+          RESPONSE=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
+            "https://api.github.com/repos/${{ github.repository }}/deployments")
+
+          # Extract the deployment ID related to the PR branch
+          PR_BRANCH=${{ github.event.pull_request.head.ref }}
+          DEPLOYMENT_ID=$(echo "$RESPONSE" | jq -r --arg branch "$PR_BRANCH" \
+            '.[] | select(.ref == $branch) | .id' | head -n 1)
+
+          if [ -z "$DEPLOYMENT_ID" ]; then
+            echo "No deployment found for this PR."
+            exit 0
+          fi
+
+          echo "Found Deployment ID: $DEPLOYMENT_ID"
+          echo "deployment_id=$DEPLOYMENT_ID" >> $GITHUB_ENV
+
+      - name: 🗑️ Remove Cloudflare Preview Deployment
+        if: env.deployment_id != ''
+        env:
+          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
+          CLOUDFLARE_ACCOUNT_ID: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
+          CLOUDFLARE_PROJECT_NAME: ${{ vars.CLOUDFLARE_PROJECT_NAME }}
+          DEPLOYMENT_ID: ${{ env.deployment_id }}
+        run: |
+          echo "Deleting Cloudflare Pages deployment: $DEPLOYMENT_ID"
+          curl -X DELETE "https://api.cloudflare.com/client/v4/accounts/$CLOUDFLARE_ACCOUNT_ID/pages/projects/$CLOUDFLARE_PROJECT_NAME/deployments/$DEPLOYMENT_ID" \
+            -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
+            -H "Content-Type: application/json" \
+            -o response.json
+
+          # Check if the deletion was successful
+          if grep -q '"success":true' response.json; then
+            echo "✅ Successfully deleted deployment."
+          else
+            echo "❌ Failed to delete deployment."
+            cat response.json
+            exit 1
+          fi
+
+      - name: 🗑️ Remove GitHub Deployment
+        if: env.deployment_id != ''
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          DEPLOYMENT_ID: ${{ env.deployment_id }}
+        run: |
+          echo "Deleting GitHub deployment: $DEPLOYMENT_ID"
+          curl -X DELETE "https://api.github.com/repos/${{ github.repository }}/deployments/$DEPLOYMENT_ID" \
+            -H "Authorization: token $GITHUB_TOKEN" \
+            -H "Accept: application/vnd.github.v3+json" \
+            -o response.json
+
+          # Check if the deletion was successful
+          if grep -q '"message":"Not Found"' response.json; then
+            echo "❌ Failed to delete GitHub deployment. Deployment not found."
+            cat response.json
+            exit 1
+          elif grep -q '"message":"Bad credentials"' response.json; then
+            echo "❌ Failed to delete GitHub deployment. Invalid credentials."
+            cat response.json
+            exit 1
+          else
+            echo "✅ Successfully deleted GitHub deployment."
+          fi
